export const donationCompletionEnums = {
    DONOR_NOT_FOUND: 0,
    INCORRECT_VERIFICATION_CODE_ANOTHER_ONE_SENT: 1,
    INCORRECT_VERIFICATION_CODE_AND_RAN_OUT_OF_CHANCES: 2,
    RAN_OUT_OF_CHANCES: 3,
    NO_PENDING_DONATION_REQUEST_FOUND: 4,
    UNEXPECTED_ERROR: 5,
}