export const donorVerificationEnums = {
    DONOR_NOT_FOUND: 0,
    INCORRECT_OTP_ANOTHER_ONE_SENT: 1,
    INCORRECT_OTP_AND_RAN_OUT_OF_CHANCES: 2,
    RAN_OUT_OF_CHANCES: 3,
    ALREADY_VERIFIED: 4,
    UNEXPECTED_ERROR: 5
}